{% set data = load_setup_py_data() %}

package:
  name: iwopy
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
  build:
    - python
    - matplotlib-base
    - numpy
    - scipy
  run:
    - python
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - iwopy
  requires:
    - pip
    - pytest
    - pymoo
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: {{ data['project_urls']['Source Code'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
  description: |
    The iwopy package is a meta package that provides interfaces 
    to other open-source Python optimization packages out there.
    